# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/drum_synthesis/drum_synthesis.tmp/i2s_data_v1_0_project/i2s_data_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/drum_synthesis/drum_synthesis.tmp/i2s_data_v1_0_project/i2s_data_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/ip_repo/i2s_data_1.0
  c:/ip_repo/adau_controller_1.0
} [current_project]
set_property ip_output_repo c:/drum_synthesis/drum_synthesis.tmp/i2s_data_v1_0_project/i2s_data_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib c:/ip_repo/i2s_data_1.0/hdl/i2s_data_v1_0.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top i2s_data_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef i2s_data_v1_0.dcp

catch { report_utilization -file i2s_data_v1_0_utilization_synth.rpt -pb i2s_data_v1_0_utilization_synth.pb }
