# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  {c:/Users/Victoria Biliouris/ip_repo/i2s_data_1.0}
  {c:/Users/Victoria Biliouris/ip_repo/adau_controller_1.0}
} [current_project]
set_property ip_output_repo {c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v}}
add_files {{C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/design_1.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/design_1_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/sources_1/bd/design_1/design_1.bd}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/constrs_1/new/contraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Victoria Biliouris/drum_synthesis/drum_synthesis.srcs/constrs_1/new/contraints.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
